// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrRSushiApi.Data;

#nullable disable

namespace MrRSushiApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521081312_AddAddOnsJsonToCartItems")]
    partial class AddAddOnsJsonToCartItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("MrRSushiApi.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddOnsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MrRSushiApi.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Featured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "sushi",
                            Description = "使用新鲜食材和特制酱料制作的招牌寿司",
                            Featured = true,
                            Image = "/images/sushi-signature.jpg",
                            IsAvailable = true,
                            Name = "招牌寿司",
                            Price = "13元"
                        },
                        new
                        {
                            Id = 2,
                            Category = "sushi",
                            Description = "鸭蛋黄寿司，口感浓郁醇厚",
                            Featured = false,
                            Image = "/images/sushi-duck.jpg",
                            IsAvailable = true,
                            Name = "鸭蛋黄寿司",
                            Price = "15元"
                        },
                        new
                        {
                            Id = 3,
                            Category = "sushi",
                            Description = "香脆培根寿司融合料理",
                            Featured = false,
                            IsAvailable = true,
                            Name = "培根寿司",
                            Price = "15元"
                        },
                        new
                        {
                            Id = 4,
                            Category = "sushi",
                            Description = "灵感来自樱花的时令风味寿司",
                            Featured = true,
                            Image = "https://images.unsplash.com/photo-1556906782-5e232862b21e?q=80&w=300&auto=format&fit=crop",
                            IsAvailable = true,
                            Name = "樱花寿司",
                            Price = "15元"
                        },
                        new
                        {
                            Id = 5,
                            Category = "sushi",
                            Description = "芝士寿司，完美融合各种风味",
                            Featured = false,
                            IsAvailable = true,
                            Name = "芝士寿司",
                            Price = "16元"
                        },
                        new
                        {
                            Id = 6,
                            Category = "sushi",
                            Description = "优质鱼子酱寿司，口感精致",
                            Featured = false,
                            IsAvailable = true,
                            Name = "鱼子酱寿司",
                            Price = "16元"
                        },
                        new
                        {
                            Id = 7,
                            Category = "sushi",
                            Description = "新鲜金枪鱼寿司，经典之选",
                            Featured = true,
                            Image = "https://images.unsplash.com/photo-1558985250-27a406d64cb3?q=80&w=300&auto=format&fit=crop",
                            IsAvailable = true,
                            Name = "金枪鱼寿司",
                            Price = "18元"
                        },
                        new
                        {
                            Id = 8,
                            Category = "sushi",
                            Description = "金枪鱼搭配鱼子酱寿司，风味丰富",
                            Featured = false,
                            IsAvailable = true,
                            Name = "金枪鱼鱼子酱寿司",
                            Price = "20元"
                        },
                        new
                        {
                            Id = 9,
                            Category = "sushi",
                            Description = "金枪鱼搭配鹌鹑蛋和芝士寿司，高级口感",
                            Featured = false,
                            IsAvailable = true,
                            Name = "金枪鱼鹌鹑蛋芝士寿司",
                            Price = "22元"
                        },
                        new
                        {
                            Id = 10,
                            Category = "sushi",
                            Description = "金枪鱼搭配鹌鹑蛋、芝士和鸭蛋黄寿司",
                            Featured = false,
                            IsAvailable = true,
                            Name = "金枪鱼鹌鹑蛋芝士+鸭蛋黄寿司",
                            Price = "24元"
                        },
                        new
                        {
                            Id = 11,
                            Category = "sushi",
                            Description = "我们终极金枪鱼组合寿司，搭配全部高级配料",
                            Featured = true,
                            Image = "https://images.unsplash.com/photo-1562802378-063ec186a863?q=80&w=300&auto=format&fit=crop",
                            IsAvailable = true,
                            Name = "金枪鱼鹌鹑蛋芝士+鸭蛋黄+培根寿司",
                            Price = "26元"
                        },
                        new
                        {
                            Id = 12,
                            Category = "handroll",
                            Description = "肉松手卷，口感鲜美可口",
                            Featured = true,
                            Image = "https://images.unsplash.com/photo-1553621042-f6e147245754?q=80&w=300&auto=format&fit=crop",
                            IsAvailable = true,
                            Name = "肉松手卷",
                            Price = "7元"
                        },
                        new
                        {
                            Id = 13,
                            Category = "handroll",
                            Description = "火腿手卷，完美的快捷小食",
                            Featured = false,
                            IsAvailable = true,
                            Name = "火腿手卷",
                            Price = "7元"
                        },
                        new
                        {
                            Id = 14,
                            Category = "handroll",
                            Description = "鱼子手卷，使用优质鱼子",
                            Featured = false,
                            IsAvailable = true,
                            Name = "鱼子手卷",
                            Price = "7元"
                        },
                        new
                        {
                            Id = 15,
                            Category = "handroll",
                            Description = "蟹棒手卷，经典之选",
                            Featured = true,
                            Image = "https://images.unsplash.com/photo-1540713304937-18ad930d3594?q=80&w=300&auto=format&fit=crop",
                            IsAvailable = true,
                            Name = "蟹棒手卷",
                            Price = "7元"
                        },
                        new
                        {
                            Id = 16,
                            Category = "handroll",
                            Description = "芝士手卷，口感细腻奶香浓郁",
                            Featured = false,
                            IsAvailable = true,
                            Name = "芝士手卷",
                            Price = "7元"
                        },
                        new
                        {
                            Id = 17,
                            Category = "pancake",
                            Description = "单蛋 + 蔬菜 + 沙拉，健康美味",
                            Featured = true,
                            Image = "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Name = "杂粮煎饼",
                            Price = "7元"
                        },
                        new
                        {
                            Id = 18,
                            Category = "pancake",
                            Description = "双蛋 + 蔬菜 + 火鸡面，美味搭配",
                            Featured = false,
                            Image = "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Name = "火鸡面煎饼",
                            Price = "12元"
                        },
                        new
                        {
                            Id = 19,
                            Category = "pancake",
                            Description = "双蛋 + 蔬菜 + 海苔 + 肉松，经典组合",
                            Featured = false,
                            Image = "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Name = "海苔肉松煎饼",
                            Price = "13元"
                        },
                        new
                        {
                            Id = 20,
                            Category = "pancake",
                            Description = "双蛋 + 蔬菜 + 培根，西式风味",
                            Featured = false,
                            Image = "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=800&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Name = "培根煎饼",
                            Price = "14元"
                        },
                        new
                        {
                            Id = 21,
                            Category = "pancake",
                            Description = "双蛋 + 蔬菜 + 肉松 + 火腿肉，创意十足",
                            Featured = false,
                            Image = "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Name = "中式汉堡煎饼",
                            Price = "16元"
                        },
                        new
                        {
                            Id = 22,
                            Category = "pancake",
                            Description = "双蛋 + 芝士 + 蔬菜 + 火鸡面，豪华美味",
                            Featured = true,
                            Image = "https://images.unsplash.com/photo-1598215439219-738c1b65700a?w=800&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Name = "火焰芝士火鸡面煎饼",
                            Price = "22元"
                        },
                        new
                        {
                            Id = 23,
                            Category = "pancake",
                            Description = "双蛋 + 芝士 + 蔬菜 + 海苔 + 肉松，多层风味",
                            Featured = false,
                            Image = "https://images.unsplash.com/photo-1567982047351-76b6f93e88ee?w=800&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Name = "火焰芝士海苔肉松煎饼",
                            Price = "23元"
                        },
                        new
                        {
                            Id = 24,
                            Category = "pancake",
                            Description = "双蛋 + 芝士 + 蔬菜 + 培根，口感丰富",
                            Featured = true,
                            Image = "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=800&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Name = "火焰芝士培根煎饼",
                            Price = "24元"
                        },
                        new
                        {
                            Id = 25,
                            Category = "pancake",
                            Description = "双蛋 + 芝士 + 蔬菜 + 肉松 + 火腿肉，奢华体验",
                            Featured = false,
                            Image = "https://images.unsplash.com/photo-1563381013529-1c922c80ac8d?w=800&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Name = "火焰芝士火腿煎饼",
                            Price = "26元"
                        });
                });

            modelBuilder.Entity("MrRSushiApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MrRSushiApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddOnsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanionDetails")
                        .HasColumnType("TEXT");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MrRSushiApi.Models.CartItem", b =>
                {
                    b.HasOne("MrRSushiApi.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("MrRSushiApi.Models.OrderItem", b =>
                {
                    b.HasOne("MrRSushiApi.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MrRSushiApi.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MrRSushiApi.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
