name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Navigate to project directory
        run: cd mr-r-sushi

      - name: Install dependencies
        working-directory: ./mr-r-sushi
        run: npm install

      - name: Build project
        working-directory: ./mr-r-sushi
        run: |
          # Use the CI build script that skips TypeScript checking
          npm run ci-build

          # Verify build was created
          if [ -d "dist" ]; then
            echo "Build completed"
          else
            echo "Build failed completely"
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: mr-r-sushi/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./dist

      - name: Prepare directory on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/html/mr-r-sushi
            sudo rm -rf /var/www/html/mr-r-sushi/*
            sudo chown -R ec2-user:ec2-user /var/www/html/mr-r-sushi

      - name: Deploy files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/**'
          target: '/var/www/html/mr-r-sushi'
          strip_components: 1
          debug: true
