name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Navigate to project directory
        run: cd mr-r-sushi

      - name: Install dependencies
        working-directory: ./mr-r-sushi
        run: npm install

      - name: Build project
        working-directory: ./mr-r-sushi
        run: |
          # Use the CI build script that skips TypeScript checking
          npm run ci-build

          # Verify build was created
          if [ -d "dist" ]; then
            echo "Build completed"
          else
            echo "Build failed completely"
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: mr-r-sushi/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./dist # 解压到工作目录

      # 1️⃣ 先用 SSH Action 修好目录权限
      - name: Prepare webroot on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo mkdir -p /var/www/html/mr-r-sushi
            sudo chown -R ec2-user:ec2-user /var/www/html/mr-r-sushi

      # 2️⃣ 再用 SCP Action 上传文件
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: 'dist/**' # 上传 dist 里所有内容
          target: '/var/www/html/mr-r-sushi'
          strip_components: 1 # 去掉 dist 这一层
          rm: true # 上传前清空旧文件
          timeout: 60s
          command_timeout: 15m
          debug: true
