name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Navigate to project directory
        run: cd mr-r-sushi

      - name: Install dependencies
        working-directory: ./mr-r-sushi
        run: npm install

      - name: Build project
        working-directory: ./mr-r-sushi
        run: |
          # Use the CI build script that skips TypeScript checking
          npm run ci-build

          # Verify build was created
          if [ -d "dist" ]; then
            echo "Build completed"
          else
            echo "Build failed completely"
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: mr-r-sushi/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./dist

      - name: Prepare directory on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/html
            sudo rm -rf /var/www/html/*
            sudo chown -R ec2-user:ec2-user /var/www/html

      - name: Deploy files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/**'
          target: '/var/www/html'
          strip_components: 1
          debug: true

      - name: Set up Nginx with SSL
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Nginx if not already installed
            if ! command -v nginx &> /dev/null; then
              sudo amazon-linux-extras install nginx1 -y || sudo yum install nginx -y
            fi

            # Upload Cloudflare certificate and key
            # Note: You need to add these as secrets in your GitHub repository
            echo "${{ secrets.SSL_CERT }}" | sudo tee /etc/nginx/cert.pem > /dev/null
            echo "${{ secrets.SSL_KEY }}" | sudo tee /etc/nginx/key.pem > /dev/null

            # Configure Nginx
            sudo tee /etc/nginx/conf.d/default.conf > /dev/null << 'EOF'
            server {
                listen 80;
                server_name _;
                
                # Redirect all HTTP to HTTPS
                return 301 https://$host$request_uri;
            }

            server {
                listen 443 ssl;
                server_name _;
                
                # SSL Certificate
                ssl_certificate /etc/nginx/cert.pem;
                ssl_certificate_key /etc/nginx/key.pem;
                
                # SSL Protocols and Ciphers
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_prefer_server_ciphers on;
                ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
                
                # Root directory
                root /var/www/html;
                index index.html;
                
                # Handle Single Page Application routing
                location / {
                    try_files $uri $uri/ /index.html;
                }
                
                # Cache static assets
                location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                    expires 30d;
                    add_header Cache-Control "public, no-transform";
                }
            }
            EOF

            # Check Nginx configuration
            sudo nginx -t

            # Restart Nginx
            sudo systemctl restart nginx

            # Enable Nginx to start on boot
            sudo systemctl enable nginx
